Shoperies/web/auth.py
from flask import Blueprint, render_template,redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from .models import *
from . import db, bcrypt
from flask import Flask, render_template
from flask_login import login_required, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')    
    password = request.form.get('password')
    user = User.query.filter_by(email=email).first()
    if not user or not bcrypt.check_password_hash(user.password, password): 
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if user doesn't exist or password is wrong, reload the page
    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=True)
    #TODO: Handle case when role is empty
    #currently agent is not assigned any role by default
    if user.roles[0].name == 'Admin':
        return redirect(url_for('main.da_list'))
    else:
        return redirect(url_for('main.agent_view'))

@auth.route('/reset_password', methods=['POST'])
def reset_password():
    current_password = request.form.get('current_password')    
    updated_password = request.form.get('updated_password')
    confirm_updated_password = request.form.get('confirm_updated_password')
    user = User.query.filter_by(email=current_user.email).first()
    if not user or not bcrypt.check_password_hash(user.password, current_password): 
        flash('The current password you entered is wrong')
        return redirect(url_for('auth.login')) # if user doesn't exist or password is wrong, reload the page
    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=True)
    #TODO: Handle case when role is empty
    #currently agent is not assigned any role by default
    if user.roles[0].name == 'Admin':
        return redirect(url_for('main.da_list'))
    else:
        return redirect(url_for('main.agent_view'))

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    name = request.form.get('username')
    email = request.form.get('email')    
    password = request.form.get('password')
    confirm_password = request.form.get('confirmpassword')
    phonenumber = request.form.get('phonenumber')

    if password != confirm_password:
        flash("Passwords don't match!")
        return redirect(url_for('auth.login'))
    user = User.query.filter_by(email=email).first() 

    if user:
        flash('Email address already exists, please login!')
        return redirect(url_for('auth.signup'))
    
    default_role = Role.query.filter_by(name='Agent').first()
    new_user = User(username=name, email=email, phone_no=phonenumber, password=bcrypt.generate_password_hash(password).decode('utf-8'), is_working=True)
    new_user.roles.append(default_role)
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

Shoperies/web/main.py
from flask import Blueprint
from . import db
from .models import *
from flask import Blueprint, render_template, redirect, url_for, flash, escape, request
from flask_login import login_required, current_user
from flask_user import roles_required
from .forms import *
from urllib.parse import quote

main = Blueprint('main', __name__)

@app.errorhandler(403)
def unauthorized(e):
    return render_template('error_page.html', error_code=403, error_message='You are not allowed to access this page!'), 403

@app.errorhandler(404)
def page_not_found(e):
    return render_template('error_page.html', error_code=404, error_message='Page Not Found!'), 404

@app.errorhandler(500)
def server_error(e):
    return render_template('error_page.html', error_code=500, error_message='Internal Server Error!'), 500

@main.route('/')
def index():
    if current_user.is_authenticated:
        if current_user.has_roles('Admin'):
            return redirect(url_for('main.da_list'))
        else:
            return redirect(url_for('main.agent_view'))
    else:
        return redirect(url_for('auth.login'))

@main.route("/da_list")
@roles_required('Admin')
@login_required
def da_list():
    agent_role = Role.query.filter_by(name='Agent').first()
    agents = db.session.query(User).filter(User.roles.contains(agent_role))
    return render_template('da_list.html', agents=agents)

@main.route("/agent/<int:agent_id>", methods=['GET'])
@roles_required('Admin')
@login_required
def agent(agent_id):
    agent = User.query.get_or_404(agent_id)
    orders = db.session.query(Order).filter(Order.user_id == agent_id, Order.status != OrderStatus.delivered).all()
    return render_template('agent.html', agent=agent, orders=orders)

@main.route("/current_orders", methods=['GET'])
@roles_required('Admin')
@login_required
def current_orders():
    page = request.args.get('page', 1 , type=int)
    orders = db.session.query(Order).filter(Order.status != OrderStatus.delivered).order_by(Order.id).paginate(page=page, per_page=8)
    return render_template('orders_list.html', orders=orders, title='List of Open Orders', base_func='current_orders')

@main.route("/delivered_orders", methods=['GET'])
@roles_required('Admin')
@login_required
def delivered_orders():
    page = request.args.get('page', 1 , type=int)
    # Delivered orders need to be in descending
    orders = db.session.query(Order).filter(Order.status == OrderStatus.delivered).order_by(Order.id.desc()).paginate(page=page, per_page=8)
    return render_template('orders_list.html', orders=orders, title='List of Delivered Orders', base_func='delivered_orders')

@main.route("/unassigned_orders", methods=['GET'])
@roles_required('Admin')
@login_required
def unassigned_orders():
    orders = db.session.query(Order.cust_pincode).filter(Order.user_id == None ,Order.status != OrderStatus.delivered).group_by(Order.cust_pincode).all()
    return render_template('pincode_list.html', orders=orders, title="Pincodes of open orders")

@main.route("/pin_orders/<string:pin>", methods=['GET'])
@roles_required('Admin')
@login_required
def pin_orders(pin):
    page = request.args.get('page', 1 , type=int)
    orders = db.session.query(Order).filter(Order.user_id == None, Order.status != OrderStatus.delivered, Order.cust_pincode == pin).order_by(Order.id).paginate(page=page, per_page=8)
    title = "Orders in " + pin
    return render_template('orders_list.html', orders=orders, title=title, base_func='pin_orders')

@main.route("/order/<int:order_id>", methods=['GET'])
@roles_required('Admin')
@login_required
def order(order_id):
    order = Order.query.get_or_404(order_id)
    agent = User.query.get(order.user_id)
    return render_template('order.html', order=order, agent=agent)

@main.route("/agent_order_view/<int:order_id>")
@roles_required('Agent')
@login_required
def detailed_order(order_id):
    order = Order.query.get_or_404(order_id)
    complete_address = order.cust_addr1
    if order.cust_addr2:
        complete_address = complete_address + ' ' + order.cust_addr2
    complete_address = complete_address + ' ' + order.cust_pincode
    # making the address url safe
    escaped_address = escape(complete_address)
    return render_template('agent_order_view.html', order=order, agent=current_user, escaped_address=escaped_address)

@main.route("/plot_agent_route/<int:agent_id>")
@roles_required('Agent')
@login_required
def plot_agent_route(agent_id):
    orders = db.session.query(Order.cust_addr1, Order.cust_addr2, Order.cust_pincode).filter(Order.user_id == agent_id, Order.status != OrderStatus.delivered).all()
    gapi_prefix = r'https://www.google.com/maps/dir//'
    #gapi_prefix = r'https://www.google.com/maps/dir/?api=1&origin=16651+Redmond+way,Redmond,+WA+98052&waypoints='
    waypoints = ''
    for order in orders:
        order_address = order.cust_addr1 + ' '
        if order.cust_addr2:
            order_address = order_address + ' ' + order.cust_addr2
        order_address = order_address + order.cust_pincode
        #waypoints = waypoints + order_address + '|'
        waypoints = waypoints + order_address + '/'
    gapi_route = gapi_prefix + quote(waypoints)
    #print("GMAPS API CALL:" + gapi_route)
    return redirect(gapi_route)

@main.route("/assign_view/<int:order_id>")
@roles_required('Admin')
@login_required
def assign_view(order_id):
    agents = User.query.filter_by(is_working=True)
    return render_template('assign_view.html', agents=agents, order_id=order_id)

@main.route("/assign_order/<int:order_id>/<int:user_id>")
@roles_required('Admin')
@login_required
def assign_order(order_id, user_id):
    order = Order.query.get_or_404(order_id)
    order.user_id = user_id
    db.session.commit()
    return redirect(url_for('main.agent', agent_id=user_id))

@main.route("/da_update_status/<int:agent_id>")
@login_required
def da_update_status(agent_id):
    agent = User.query.get_or_404(agent_id)
    agent.is_working = not agent.is_working
    db.session.commit()
    return (redirect(url_for('main.agent', agent_id=agent.id)))

@main.route("/update_order_status/<int:order_id>/<string:status_option>", methods=['GET', 'POST'])
@roles_required('Admin')
@login_required
def update_order_status(order_id, status_option):
    order = Order.query.get_or_404(order_id)
    order.status = OrderStatus[status_option]
    db.session.commit()
    message_body = 'Kanishka Redmond Update\nOrder ID: {}\nStatus: {}'.format(str(order.id), str(order.status))
    # should work on iOS 8+ and Android (only for single sender and message)
    # Ref https://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link
    sms_string = 'sms:{};?&body={}'.format(str(order.phone), message_body)
    return redirect(sms_string)

@main.route("/get_order_status/<int:order_id>", methods=['GET', 'POST'])
@login_required
def get_order_status(order_id):
    order = Order.query.get_or_404(order_id)
    return '<span class="badge badge-dark">{}</span>'.format(order.status)

@main.route("/update_order_status_agent/<int:order_id>/<string:status_option>", methods=['GET', 'POST'])
@roles_required('Agent')
@login_required
def update_order_status_agent(order_id, status_option):
    order = Order.query.get_or_404(order_id)
    order.status = OrderStatus[status_option]
    db.session.commit()
    message_body = 'Kanishka Redmond Update\nOrder ID: {}\nStatus: {}'.format(str(order.id), str(order.status))
    sms_string = 'sms:{};?&body={}'.format(str(order.phone), message_body)
    return redirect(sms_string)

@main.route("/create_order", methods=['GET', 'POST'])
@roles_required('Admin')
@login_required
def create_order():
    create_order_form = OrderItemsForm()
    if create_order_form.validate_on_submit(): 
        new_order = Order(status=create_order_form.status.data, cust_name=create_order_form.cust_name.data, phone=create_order_form.phone.data,cust_addr1=create_order_form.cust_addr1.data, cust_addr2=create_order_form.cust_addr2.data,cust_pincode=create_order_form.cust_pincode.data, delivery_instructions=create_order_form.delivery_instructions.data,user_tip=create_order_form.user_tip.data)
        db.session.add(new_order)
        db.session.commit()
        flash('Order created successfully!', 'success')
        return (redirect(url_for('main.create_order')))
    return render_template('create_order.html', form=create_order_form)

@main.route("/edit_order/<int:order_id>", methods=['GET', 'POST'])
@roles_required('Admin')
@login_required
def edit_order(order_id):
    order = Order.query.get_or_404(order_id)
    order.status=OrderStatus(order.status).name
    edit_order_form = OrderItemsForm(obj=order)
    if edit_order_form.validate_on_submit(): 
        update_existing_order(order, edit_order_form)
        db.session.commit()
        flash('Order updated successfully!', 'success')
        return (redirect(url_for('main.current_orders')))
    return render_template('edit_order.html', form=edit_order_form, order_id=order_id)

@main.route("/delete_order/<int:order_id>", methods=['GET', 'POST'])
@roles_required('Admin')
@login_required
def delete_order(order_id):
    order = Order.query.get_or_404(order_id)
    if order:
        db.session.delete(order)
        db.session.commit()
        flash('Order Deleted successfully!', 'success')
        return (redirect(url_for('main.current_orders')))
    agent = User.query.get(order.user_id)
    return render_template('order.html', order=order, agent=agent)

def update_existing_order(order, form):
    order.status = form.status.data
    order.cust_name = form.cust_name.data
    order.phone = form.phone.data
    order.cust_addr1 = form.cust_addr1.data
    order.cust_addr2 = form.cust_addr2.data
    order.cust_pincode = form.cust_pincode.data
    order.delivery_instructions = form.delivery_instructions.data
    order.user_tip = form.user_tip.data

@main.route("/agent_view")
@login_required
def agent_view():
    page = request.args.get('page', 1 , type=int)

Shoperies/web/templates/admin_layout.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>Delivery Application</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('main.da_list') }}">Hello {{current_user.username}}!</a>
        <div class="navbar">
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Reset Password</a>
            <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('main.da_list') }}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages =  get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{category}}">
                      {{ message }}
                  </div>
              {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Actions</h3>
          <p class='text-muted'>
          <ul class="list-group">
            <a href="{{ url_for('main.create_order') }}">
              <li class="list-group-item list-group-item-light">Create Order</li>
            </a>
            <a href="{{ url_for('main.unassigned_orders') }}">
              <li class="list-group-item list-group-item-light">Unassigned Orders</li>
            </a>
            <a href="{{ url_for('main.current_orders') }}">
              <li class="list-group-item list-group-item-light">Current Orders</li>
            </a>
            <a href="{{ url_for('main.delivered_orders') }}">
              <li class="list-group-item list-group-item-light">Delivered Orders</li>
            </a>
            <a href="{{ url_for('main.da_list') }}">
              <li class="list-group-item list-group-item-light">Delivery Agent List</li>
            </a>
          </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
</body>

</html>

Shoperies/web/templates/agent_assigned_orders_view.html
{% extends "agent_layout.html" %}
{% block content %}
{% if agent.is_working == True %}
{% set status = 'Available' %}
{% set opp_status = 'Un-Available' %}
{% set badge_type = 'primary' %}
{% else %}
{% set status = 'Un-Available' %}
{% set opp_status = 'Available' %}
{% set badge_type = 'danger' %}
{% endif %}
<div class="container card">
  <div class="row card-body">
    <div class="col">
      {{ agent.username }}
    </div>
    <div class="col">
      <a href="tel:{{agent.phone_no}}">{{agent.phone_no}}</a>
    </div>
    <div class="col">
      <span class="badge badge-dark">Orders:{{orders.items|length}}</span>
    </div>
    <div class="col">
      <span class="badge badge-{{ badge_type }}">{{ status }}</span>
    </div>
  </div>
  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.da_update_status', agent_id=agent.id) }}">Make
    {{opp_status}}</a>
</div>
<br>
{% if orders %}
<div class="container card text-left text-white bg-dark">
  <div class="row card-body">
    <div class="col">
      Order ID
    </div>
    <div class="col">
      Customer
    </div>
    <div class="col">
      Status
    </div>
  </div>
</div>
{% for order in orders.items %}
<div class="container card">
  <a class="nav-item nav-link" href="{{ url_for('main.detailed_order', order_id=order.id) }}">
    <div class="row card-body">
      <div class="col">
        {{ order.id }}
      </div>
      <div class="col">
        {{ order.cust_name }}
      </div>
      <div class="col">
        <span class="badge badge-dark">{{ order.status }}</span>
      </div>
    </div>
  </a>
</div>
{% endfor %}
<br><br>
<div class="mr-2 col col-md-4">
  <a class="btn btn-primary" href="{{ url_for('main.plot_agent_route', agent_id=agent.id) }}" target="_blank">My Route</a>
</div>
{% else %}
<br>
<div class="text-black text-center font-weight-bold">
  This agent has no orders yet.
</div>
{% endif %}
<br>
<div class="float-right">
  {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  {% if orders.page == page_num %}
  <a class="btn btn-info mb-4" href="{{ url_for('main.agent_view', page=page_num) }}">{{ page_num }}</a>
  {% else %}
  <a class="btn btn-outline-info mb-4" href="{{ url_for('main.agent_view', page=page_num) }}">{{ page_num }}</a>
  {% endif %}
  {% else %}
  {% endif%}
  {% endfor %}
</div>
{% endblock content %}

Shoperies/web/templates/agent_dorders.html
{% extends "agent_layout.html" %}
{% block content %}
{% if agent.is_working == True %}
{% set status = 'Available' %}
{% set opp_status = 'Un-Available' %}
{% set badge_type = 'primary' %}
{% else %}
{% set status = 'Un-Available' %}
{% set opp_status = 'Available' %}
{% set badge_type = 'danger' %}
{% endif %}
<br>
<div class="text-black text-center">
  {{ title }}
</div>
<br>
<div class="container card text-left text-white bg-dark">
  <div class="row card-body">
    <div class="col">
      Order ID
    </div>
    <div class="col">
      Customer
    </div>
    <div class="col">
      Status
    </div>
  </div>
</div>
{% if orders %}
{% for order in orders.items %}
<div class="container card">
  <a class="nav-item nav-link" href="{{ url_for('main.detailed_order', order_id=order.id) }}">
    <div class="row card-body">
      <div class="col">
        {{ order.id }}
      </div>
      <div class="col">
        {{ order.cust_name }}
      </div>
      <div class="col">
        <span class="badge badge-dark">{{ order.status }}</span>
      </div>
    </div>
  </a>
</div>
{% endfor %}
{% else %}
<br><br>
<div class="text-center font-weight-bold">
  No orders here yet.
</div>
{% endif %}
<br>
<div class="float-right">
  {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  {% if orders.page == page_num %}
  <a class="btn btn-info mb-4" href="{{ url_for('main.agent_dorders', page=page_num) }}">{{ page_num }}</a>
  {% else %}
  <a class="btn btn-outline-info mb-4" href="{{ url_for('main.agent_dorders', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
      {% endif%}
    {% endfor %}
  </div>
{% endblock content %}

Shoperies/web/templates/agent_layout.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>Delivery Agent View</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('main.agent_view') }}">Hello {{current_user.username}}!</a>
        <div class="navbar">
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('main.da_list') }}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
          {% for category, message in messages %}
              <div class="alert alert-{{category}}">
                  {{ message }}
              </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Actions</h3>
          <p class='text-muted'>
          <ul class="list-group">
            <a href="{{ url_for('main.agent_view') }}">
              <li class="list-group-item list-group-item-light">My Orders</li>
            </a>
            <!-- <a href="{{ url_for('main.unassigned_orders') }}" >
                  <li class="list-group-item list-group-item-light">Unassigned Orders</li>
                </a> -->
            <!-- TODO: Make this as orders assigned but not ready for delivery -->
            <!-- <a href="#" >
                  <li class="list-group-item list-group-item-light">Current Orders</li>
                </a> -->
            <a href="{{ url_for('main.agent_dorders') }}">
              <li class="list-group-item list-group-item-light">Delivered Orders</li>
            </a>
          </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
</body>

</html>

Shoperies/web/templates/assign_view.html
{% extends "admin_layout.html" %}
{% block content %}
<br>
<div class="text-black text-center">
  List of Available Delivery Agents
</div>
<br>
<div class="container card text-left text-white bg-dark">
  <div class="row card-body">
    <div class="col">
      Agent Name
    </div>
    <div class="col">
      Phone No
    </div>
  </div>
</div>
{% for agent in agents %}
{% if agent.is_working == True %}
{% set status = 'Available' %}
{% set badge_type = 'primary' %}
{% else %}
{% set status = 'Un-Available' %}
{% set badge_type = 'danger' %}
{% endif %}
<div class="container card text-primary">
  <a class="nav-item nav-link" href="{{ url_for('main.assign_order', order_id=order_id, user_id=agent.id) }}">
    <div class="row card-body">
      <div class="col">
        {{ agent.username }}
      </div>
      <div class="col">
        {{ agent.phone_no }}
      </div>
    </div>
  </a>
</div>
{% endfor %}
{% endblock content %}

Shoperies/web/templates/orders_list.html
{% extends "admin_layout.html" %}
{% block content %}
<br>
<div class="text-black text-center">
  {{ title }}
</div>
<br>
<div class="container card text-left text-white bg-dark">
  <div class="row card-body">
    <div class="col">
      Order ID
    </div>
    <div class="col">
      Customer
    </div>
    <div class="col">
      Status
    </div>
  </div>
</div>
{% if orders %}
{% for order in orders.items %}
<div class="container card">
  <a class="nav-item nav-link" href="{{ url_for('main.order', order_id=order.id) }}">
    <div class="row card-body">
      <div class="col">
        {{ order.id }}
      </div>
      <div class="col">
        {{ order.cust_name }}
      </div>
      <div class="col">
        <span class="badge badge-dark">{{ order.status }}</span>
      </div>
    </div>
  </a>
</div>
{% endfor %}
{% else %}
<br><br>
<div class="text-center font-weight-bold">
  No orders here yet.
</div>
{% endif %}
<br>
<div class="float-right">
  {% if base_func == 'delivered_orders' %}
  {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  {% if orders.page == page_num %}
  <a class="btn btn-info mb-4" href="{{ url_for('main.delivered_orders', page=page_num) }}">{{ page_num }}</a>
  {% else %}
  <a class="btn btn-outline-info mb-4" href="{{ url_for('main.delivered_orders', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
        {% endif%}
      {% endfor %}
    {% elif base_func == 'current_orders'%}
      {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if orders.page == page_num %}
            <a class=" btn btn-info mb-4" href="{{ url_for('main.current_orders', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.current_orders', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
        {% endif%}
      {% endfor %}
    {% elif base_func == 'pin_orders'%}
      {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if orders.page == page_num %}
            <a class=" btn btn-info mb-4" href="{{ url_for('main.pin_orders', pin=orders.items[0].cust_pincode, page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.pin_orders', pin=orders.items[0].cust_pincode, page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
        {% endif%}
      {% endfor %}
    {% endif %}
  </div>
{% endblock content %}

Shoperies/web/templates/pincode_list.html
{% extends "admin_layout.html" %}
{% block content %}
<br>
<div class="text-black text-center">
  {{ title }}
</div>
<br>
<div class="container card text-left text-white bg-dark">
  <div class="row card-body">
    <div class="col">
      Pincode
    </div>
  </div>
</div>
{% if orders %}
{% for order in orders %}
<div class="container card">
  <a class="nav-item nav-link" href="{{ url_for('main.pin_orders', pin=order.cust_pincode) }}">
    <div class="row card-body">
      <div class="col">
        {{ order.cust_pincode }}
      </div>
    </div>
  </a>
</div>
{% endfor %}
{% else %}
<br><br>
<div class="text-center font-weight-bold">
  No orders here yet.
</div>
{% endif %}
{% endblock content %}